### ISSUE TITLE
System Information Leak：Internal

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [NetApp/recline#3]
https://github.com/NetApp/recline/blob/5feca19c26197cf3ccc23bdb2b2cd253351d83fd/recline/vendor/argcomplete/my_shlex.py#L144
An internal information leak occurs when system data or debugging information is sent to a local file, console, or screen via printing or logging.
It is recommended to use concise and ambiguous information to prompt the user

**Comment by RobertBlackhart** [comment]
This code is part of an included third party library. Further, it is only accessible when that library is being used in debug mode which does not occur as part of using recline. I don't see anything here that needs fixing so closing the issue.
